---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# preprivalry

The goal of **preprivalry** is the preprocessing of binocular rivalry data which were collected via PsychToolbox in MATLAB environment in the project TRANSRIV by NeuroVision research group in the University of Graz. A rivalry data-set can be preprocessed by using this package if it is organized as required.

## Installation

You can install the released version of preprivalry from [CRAN](https://CRAN.R-project.org) with:

``` r
devtools::install_git('https://github.com/cemreyilmaz/preprivalry')
```

The sample data-set provided with the package has been created by using the real data recruited during the project TRANSRIV. They are the raw data and debugged manually if there is any missing key events.Please note that the subject IDs and the run numbers are faked to keep the data even more confidential.

You can check the vignettes for detailed explanation of preprocessing and further applications provided in this package.
